apps/django-web/learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # 该模块定义了可在管理网站中请求的所有URL
    path('learning_logs/', include('learning_logs.urls', namespace='learning_logs')),
                                     # 包含了namespace,将learning_logs的URL同项目中其它URL分开来
    path('users/', include('users.urls', namespace='users')),
]

apps/django-web/learning_log/learning_logs/urls.py
"""
ps: 这是要自己建立的文件, 定义learning_logs的URL模式
功能: 将URL映射到views"""

from django.conf.urls import url
from django.urls import re_path

from . import views

app_name = 'learning_logs'
# 包含了可在learning_logs应用程序中请求的所有页面(正在匹配url, 调用视图函数
urlpatterns = [  # 最后一个参数, 能够让我们在其它地方引用它(如需要提供该主页登录链接, 而不是写URL)
    # 主页 /learning_logs/
    url('^$', views.index, name='index'),
    # 主题 /learning_logs/topics/
    url(r'^topics/$', views.topics, name='topics'),
    # 特定主题的详细页面((?P<topic_id>\d+)将捕获任何数值赋值给实参topic_id)
    # url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # 详细页面/learning_logs/topics/1/   topic_id实参将被传递给topic函数处理
    re_path('topics/(?P<topic_id>\d+)/', views.topic, name='topic'),
    # 用于添加新主题的网页
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

apps/django-web/learning_log/users/urls.py
"""为应用程序users定义URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

# 使用Django提供的默认登录视图

app_name = 'users'
urlpatterns = [
    # 登录界面
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    # 注册页面
    url(r'^register/$', views.register, name='register'),
]

apps/django-web/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

"""在代码城层模型就是类"""

# Create your models here.
# Django的Model是一个定义了模型基本功能的类


class Topic(models.Model):
    """用户学习的主题(仅有两个属性text, date_added)"""
    text = models.CharField(max_length=200)                # 文本组成(200字符)
    date_added = models.DateTimeField(auto_now_add=True)  # 自动记录日期时间
    owner = models.ForeignKey(User, on_delete=True)       # 添加关联后,特定条目与特定主题相关联

    def __str__(self):
        return self.text                                  # 默认使用该属性显示有关主题的信息


class Entry(models.Model):
    """学到有关某个主题的具体知识(为添加的条目定义本模型(多对一))"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # 外键(将每个条目关联到主题)
    text = models.TextField()                                   # 不限制条目长度的text
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:                        # 存储用于管理模型的额外信息(能够设置一个特殊属性)
        verbose_name_plural = 'entries'  # 需要时,可用其表示多个条目(否则Django将使用Entrys表示)

    def __str__(self):
        """返回模型的字符串表示"""
        text = self.text[:50]
        return text + '...' if len(text) > 50 else text

apps/django-web/learning_log/users/models.py
from django.db import models

# Create your models here.

apps/django-web/learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']      # 字段名
        labels = {'text': ''}  # 不生成标签


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}  # 字段的小部件

apps/django-web/learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
# Create your views here.

# render()根据视图提供的数据渲染响应
# 参数1(原始请求), 参数2(用于创建网页的模板)


def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


@login_required                                      # 限制访问的装饰器(已登录?)
def topics(request):
    """显示所有的主题"""                             # 该语句将使用户只能看到自己的主题
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    # topics = Topic.objects.order_by('date_added')  # 从数据库中获取一些数据(可以看到所有用户的)
    context = {'topics': topics}                     # 然后发给模板
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    check_topic_owner(topic.owner, request.user)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据: 创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user  # 将新主题的属性设置为当前用户
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定的护体中添加新条目"""
    topic = Topic.objects.get(pk=topic_id)
    check_topic_owner(topic.owner, request.user)
    if request.method != 'POST':
        # 未提交数据,创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)  # 使其创建一个新的条目对象
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(pk=entry_id)
    topic = entry.topic
    check_topic_owner(topic.owner, request.user)
    if request.method != 'POST':
        # 初次请求,使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def check_topic_owner(owner, user):
    """核对当前用户和主题用户是否相符"""
    if owner != user:
        raise Http404

apps/django-web/learning_log/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单(默认提供的)
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录,再重定向到主页(正确的话返回一个通过身份验证的用户对象)
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

apps/django-web/learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
<div class="container">
    <div class="navbar-hearder">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
    </div>
    <div id="navbar" class="navbar-collapse collapase">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}.</a></li>
                 <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
                 <li><a href="{% url 'users:register' %}">Register</a></li>
                 <li><a href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
        </ul>
    </div> <!-- /.nav-collapse -->
</div>
</nav>
<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div> <!-- /container -->
</body>
</html>

apps/django-web/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% load bootstrap3 %}

{% block content %}
<body>
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}
    </form>
</body>
{% endblock content %}

apps/django-web/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
</h2>
{% endblock content %}

apps/django-web/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% endblock header %}

{% block content %}
<body>
    <p><a href="{% url 'learning_logs:topic'  topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons %}
    </form>
</body>
</html>
{% endblock content %}

apps/django-web/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% endblock header %}

{% block content %}
<body>
    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    </form>
</body>
</html>
{% endblock content %}

apps/django-web/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div> <!-- panel -->
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}
{% endblock content %}

apps/django-web/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h1>Topics</h1>
{% endblock header %}

{% block content %}
  <ul>
    {% for topic in topics %}
    <li>
    <h1>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h1>
    </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</a></h3>
{% endblock content %}

apps/django-web/learning_log/users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}

apps/django-web/learning_log/users/templates/users/register.html
{% extends "learning_logs/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Register</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}
</body>
</html>